module.exports = {
  defaultServerResponse: {
    message: "",
    body: null,
    errors: {},
    status: 400,
  },
  UserMessage: {
    USER_REGISTERED: "USER Registered Successfully",
    USER_FETCHED: "USER Fetched Successfully",
    USER_NOT_FETCHED: "USER Fetched Successfully",
    USER_LOGEDIN: "USER Logedin Successfully",
    USER_NOT_LOGEDIN: "USER Not Logedin",
    USER_UPDATED: "USER Updated Successfully",
    USER_NOT_UPDATED: "USER Not Updated Successfully",
    USER_DELETED: "USER Deleted Successfully",
    USER_NOT_DELETED: "USER Not Deleted",
    USER_NOT_FOUND: "USER Not Found",
    USER_FOUND: "USER Found",
  },
  CategoryMessage: {
    CATEGORY_CREATED: "CATEGORY Created Successfully",
    CATEGORY_FETCHED: "CATEGORY Fetched Successfully",
    CATEGORY_NOT_FETCHED: "CATEGORY Fetched Successfully",
    CATEGORY_LOGEDIN: "CATEGORY Logedin Successfully",
    CATEGORY_NOT_LOGEDIN: "CATEGORY Not Logedin",
    CATEGORY_UPDATED: "CATEGORY Updated Successfully",
    CATEGORY_NOT_UPDATED: "CATEGORY Not Updated Successfully",
    CATEGORY_DELETED: "CATEGORY Deleted Successfully",
    CATEGORY_NOT_DELETED: "CATEGORY Not Deleted",
    CATEGORY_NOT_FOUND: "CATEGORY Not Found",
  },
  LanguageMessage: {
    LANGUAGE_CREATED: "Language Created Successfully",
    LANGUAGEL_FETCHED: "Language Fetched Successfully",
    LANGUAGE_NOT_FETCHED: "Language Fetched Successfully",
    LANGUAGE_LOGEDIN: "LANGUAGE Logedin Successfully",
    LANGUAGE_NOT_LOGEDIN: "LANGUAGE Not Logedin",
    LANGUAGE_UPDATED: "LANGUAGE Updated Successfully",
    LANGUAGE_NOT_UPDATED: "LANGUAGE Not Updated Successfully",
    LANGUAGE_DELETED: "LANGUAGE Deleted Successfully",
    LANGUAGE_NOT_DELETED: "LANGUAGE Not Deleted",
    LANGUAGE_NOT_FOUND: "LANGUAGE Not Found",
  },
  LevelMessage: {
    LEVEL_CREATED: "level Created Successfully",
    LEVEL_FETCHED: "level Fetched Successfully",
    LEVEL_NOT_FETCHED: "LEVEL Fetched Successfully",
    LEVEL_LOGEDIN: "LEVEL Logedin Successfully",
    LEVEL_NOT_LOGEDIN: "LEVEL Not Logedin",
    LEVEL_UPDATED: "LEVEL Updated Successfully",
    LEVEL_NOT_UPDATED: "LEVEL Not Updated Successfully",
    LEVEL_DELETED: "LEVEL Deleted Successfully",
    LEVEL_NOT_DELETED: "LEVEL Not Deleted",
    LEVEL_NOT_FOUND: "LEVEL Not Found",
  },
  TopicMessage: {
    TOPIC_CREATED: "TOPIC Created Successfully",
    TOPIC_FETCHED: "TOPIC Fetched Successfully",
    TOPIC_NOT_FETCHED: "TOPIC Fetched Successfully",
    TOPIC_LOGEDIN: "TOPIC Logedin Successfully",
    TOPIC_NOT_LOGEDIN: "TOPIC Not Logedin",
    TOPIC_UPDATED: "TOPIC Updated Successfully",
    TOPIC_NOT_UPDATED: "TOPIC Not Updated Successfully",
    TOPIC_DELETED: "TOPIC Deleted Successfully",
    TOPIC_NOT_DELETED: "TOPIC Not Deleted",
    TOPIC_NOT_FOUND: "TOPIC Not Found",
  },
  SubCategoryMessage: {
    SUB_CATEGORY_CREATED: "SUB_CATEGORY Created Successfully",
    SUB_CATEGORY_FETCHED: "SUB_CATEGORY Fetched Successfully",
    SUB_CATEGORY_NOT_FETCHED: "SUB_CATEGORY Fetched Successfully",
    SUB_CATEGORY_LOGEDIN: "SUB_CATEGORY Logedin Successfully",
    SUB_CATEGORY_NOT_LOGEDIN: "SUB_CATEGORY Not Logedin",
    SUB_CATEGORY_UPDATED: "SUB_CATEGORY Updated Successfully",
    SUB_CATEGORY_NOT_UPDATED: "SUB_CATEGORY Not Updated Successfully",
    SUB_CATEGORY_DELETED: "SUB_CATEGORY Deleted Successfully",
    SUB_CATEGORY_NOT_DELETED: "SUB_CATEGORY Not Deleted",
    SUB_CATEGORY_NOT_FOUND: "SUB_CATEGORY Not Found",
  },
};
