module.exports = {
  defaultServerResponse: {
    message: "",
    body: null,
    errors: {},
    status: 400,
  },

  validationMessage: {
    VALIDATION_FAILED: "Validation Failed",
    TOKEN_MISSING: "Token is Missing, Login First",
  },

  authMessage: {
    EMAIL_EXISTS: "Email already Exists!",
    NEED_VERIFICATION: "Account Exists, Need Verification",
    NEED_LOGIN: "Account Exists, Need Login",
    ACCOUNT_DISABLED: "Sorry Your Account is Disabled",
    ACCOUNT_NOT_VERIFIED: "Your Account is Not Verified, Verify First",
    INVALID_EMAIL: "Invalid Email!",
    OTP_FAILED: "OTP Failed",
    OTP_SUCCESS: "OTP Send Successfully !",
    INVALID_PASSWORD: "Password is Wrong!",
    LOGIN_SUCCESS: "Successfully Logedin",
    LOGIN_FAILED: "Login Failed !",
    REGISTRATION_SUCCESS: "Registration Successfully !",
    REGISTRATION_FAILED: "Registration Failed !",
    ACCOUNT_VALIDATED: "Account Validated Successfully !",
  },

  adminMessage: {
    CUSTOMER_CREATED: "Admin Register Successfully!",
    PASSWORD_UPDATED: "Password Updated Successfully!",
    PASSWORD_NOT_UPDATED: "OOPS ! Password Not Updated !",
    OLD_PASSWORD_NOT_MATCHED: "OOPS ! Old Password is not Matched !",
    PROFILE_NOT_UPDATED: "OOPS ! Profile Not Updated !",
    PROFILE_UPDATED: "Profile Updated Successfully !",
    PROFILE_FETCHED: "Profile Fetched Successfully !",
    ACCOUNT_FOUND: "Account Found Successfully !",
    ACCOUNT_NOT_FOUND: "Account Not Found !",
    PROFILE_NOT_FETCHED: "OOPS ! Profile Not Fetched !",
  },

  userMessage: {
    USER_REGISTERED: "User Registered Successfully",
    USER_FETCHED: "User Fetched Successfully",
    USER_NOT_FETCHED: "User Fetched Successfully",
    USER_LOGEDIN: "User Logedin Successfully",
    USER_NOT_LOGEDIN: "User Not Logedin",
    USER_UPDATED: "User Updated Successfully",
    USER_NOT_UPDATED: "User Not Updated",
    USER_DELETED: "User Deleted Successfully",
    USER_NOT_DELETED: "User Not Deleted",
    USER_NOT_FOUND: "User Not Found",
    USER_FOUND: "User Found",
  },
  categoryMessage: {
    CATEGORY_CREATED: "Category Created Successfully",
    CATEGORY_FETCHED: "Category Fetched Successfully",
    CATEGORY_NOT_FETCHED: "Category Not Fetched ",
    CATEGORY_LOGEDIN: "Category Logedin Successfully",
    CATEGORY_NOT_LOGEDIN: "Category Not Logedin",
    CATEGORY_UPDATED: "Category Updated Successfully",
    CATEGORY_NOT_UPDATED: "Category Not Updated ",
    CATEGORY_DELETED: "Category Deleted Successfully",
    CATEGORY_NOT_DELETED: "Category Not Deleted",
    CATEGORY_NOT_FOUND: "Category Not Found",
  },
  languageMessage: {
    LANGUAGE_CREATED: "Language Created Successfully",
    LANGUAGEL_FETCHED: "Language Fetched Successfully",
    LANGUAGE_NOT_FETCHED: "Language Not Fetched",
    LANGUAGE_LOGEDIN: "Language Logedin Successfully",
    LANGUAGE_NOT_LOGEDIN: "Language Not Logedin",
    LANGUAGE_UPDATED: "Language Updated Successfully",
    LANGUAGE_NOT_UPDATED: "Language Not Updated ",
    LANGUAGE_DELETED: "Language Deleted Successfully",
    LANGUAGE_NOT_DELETED: "Language Not Deleted",
    LANGUAGE_NOT_FOUND: "Language Not Found",
  },
  levelMessage: {
    LEVEL_CREATED: "level Created Successfully",
    LEVEL_FETCHED: "level Fetched Successfully",
    LEVEL_NOT_FETCHED: "Level Not Fetched",
    LEVEL_LOGEDIN: "Level Logedin Successfully",
    LEVEL_NOT_LOGEDIN: "Level Not Logedin",
    LEVEL_UPDATED: "Level Updated Successfully",
    LEVEL_NOT_UPDATED: "Level Not Updated ",
    LEVEL_DELETED: "Level Deleted Successfully",
    LEVEL_NOT_DELETED: "Level Not Deleted",
    LEVEL_NOT_FOUND: "Level Not Found",
  },
  courseMessage: {
    COURSE_CREATED: "Course  Created Successfully",
    COURSE_NOT_CREATED: "Course Not Created Successfully",
    COURSE_FETCHED: "Course Fetched Successfully",
    COURSE_NOT_FETCHED: "Course Not Fetched",
    COURSE_LOGEDIN: "Course Logedin Successfully",
    COURSE_NOT_LOGEDIN: "Course Not Logedin",
    COURSE_UPDATED: "Course Updated Successfully",
    COURSE_NOT_UPDATED: "Course Not Updated",
    COURSE_DELETED: "Course Deleted Successfully",
    COURSE_NOT_DELETED: "Course Not Deleted",
    COURSE_NOT_FOUND: "Course Not Found",
  },
  topicMessage: {
    TOPIC_CREATED: "Topic Created Successfully",
    TOPIC_FETCHED: "Topic Fetched Successfully",
    TOPIC_NOT_FETCHED: "Topic Not Fetched",
    TOPIC_LOGEDIN: "Topic Logedin Successfully",
    TOPIC_NOT_LOGEDIN: "Topic Not Logedin",
    TOPIC_UPDATED: "Topic Updated Successfully",
    TOPIC_NOT_UPDATED: "Topic Not Updated Successfully",
    TOPIC_DELETED: "Topic Deleted Successfully",
    TOPIC_NOT_DELETED: "Topic Not Deleted",
    TOPIC_NOT_FOUND: "Topic Not Found",
  },
  reviewsMessage: {
    REVIEWS_CREATED: "Reviews Created Successfully",
    REVIEWS_FETCHED: "Reviews Fetched Successfully",
    REVIEWS_NOT_FETCHED: "Reviews Not Fetched",
    REVIEWS_UPDATED: "Reviews Updated Successfully",
    REVIEWS_NOT_UPDATED: "Reviews Not Updated",
    REVIEWS_DELETED: "Reviews Deleted Successfully",
    REVIEWS_NOT_DELETED: "Reviews Not Deleted",
    REVIEWS_NOT_FOUND: "Reviews Not Found",
  },
  subCategoryMessage: {
    SUB_CATEGORY_CREATED: "Subcategory Created Successfully",
    SUB_CATEGORY_FETCHED: "Subcategory Fetched Successfully",
    SUB_CATEGORY_NOT_FETCHED: "Subcategory Not Fetched",
    SUB_CATEGORY_LOGEDIN: "Subcategory Logedin Successfully",
    SUB_CATEGORY_NOT_LOGEDIN: "Subcategory Not Logedin",
    SUB_CATEGORY_UPDATED: "Subcategory Updated Successfully",
    SUB_CATEGORY_NOT_UPDATED: "Subcategory Not Updated",
    SUB_CATEGORY_DELETED: "Subcategory Deleted Successfully",
    SUB_CATEGORY_NOT_DELETED: "Subcategory Not Deleted",
    SUB_CATEGORY_NOT_FOUND: "Subcategory Not Found",
  },
};
